name: build and push to ghcr.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image:
    name: build and deploy image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: build image and push to registries
        id: build-push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          build-args: |
            GITHUB_REVISION=${{ github.ref }}
            GITHUB_REPOSITORY=${{ github.repository }}
          tags: |
            ghcr.io/muelheimmodular/og-image:latest